//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.Classwork.Proyecto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoArticuloPerdidoEntities : DbContext
    {
        public ProyectoArticuloPerdidoEntities()
            : base("name=ProyectoArticuloPerdidoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticuloPerdido> ArticuloPerdido { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Custodia> Custodia { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
