//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulatina.Electiva.Classwork.Proyecto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int ID { get; set; }
        public string LEVEL { get; set; }
        public string CALLSITE { get; set; }
        public string TYPE { get; set; }
        public string MESSAGE { get; set; }
        public string STACKTRACE { get; set; }
        public string INNEREXCEPTION { get; set; }
        public string ADDITIONALINFO { get; set; }
        public System.DateTime LoggedOnDate { get; set; }
    }
}
